### ISSUE TITLE
@import "bootstrap-sprokets"; leads to "undefined method `start_with?' for nil:NilClass" error

### ISSUE THREAD

**Issue by depili** [twbs/bootstrap-sass#930]
After bumping the rails-stack up to 4.2.1 I started getting a mystic "undefined method 'start_with?' for nil:NillClass' on the line my layout included the stylesheet_link_tag. Digging deeper I found out that this error goes away when I comment the "@import "bootstrap-sprockets"; line from my master stylesheet.

My complete gemfile:
```
source 'https://rubygems.org'

gem 'rails', '~> 4.2.1'

# Database interfaces
# gem 'sqlite3'
gem 'pg', '~> 0.18.2'

# For migrating from mysql to postgresql
# gem 'yaml_db', github: 'jetthoughts/yaml_db', ref: 'fb4b6bd7e12de3cffa93e0a298a1e5253d7e92ba'
# gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0.3'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby
gem "therubyracer", :require => 'v8'


# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'jquery-ui-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.3'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.1',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development

# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.10'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

#### END OF RAILS DEFAULT GEMFILE

# Twitter bootstrap for base css styling
gem 'bootstrap-sass'
# Bootstrap aware formbuilder 
gem 'bootstrap_form'

# Nokogiri for XML processing
gem 'nokogiri'

# font-awesome-sass for icons
gem 'font-awesome-sass'

# Better memcached interface
gem 'dalli'

# Sorting slides in groups etc
gem 'ranked-model'

# Use thin as the webserver
gem 'thin'

# f.error_messages
gem 'dynamic_form'

# Calculate difference between two timestamps
gem 'time_diff', '~> 0.3'

# Slim template engine
gem 'slim'
# Generators for slim templates instead of erb
gem 'slim-rails'

git 'https://github.com/depili/websocket-rails.git', branch: 'channel_token_fix' do
	gem 'websocket-rails'
end

# Alternative websocket gem, we are moving to this in steps as websocket-rails isn't maintained
gem 'tubesock'

# For background stuff
gem 'delayed_job_active_record'
gem 'daemons'
gem 'daemon'

# For monitorin scripts
gem 'highline'

# Better caching
gem 'cashier'

# for zipping all slides in a group or presentation
gem 'rubyzip', require: 'zip'

# For simple-edit previews to work in development
gem 'rack-rewrite'

# Pry for better console
gem 'pry-rails'

group :development do
  gem "rails-erd"
  gem 'web-console'
end

# Profiling support
group :profile do
  gem 'ruby-prof'
	gem 'request_profiler', :git => 'git://github.com/cheald/request_profiler.git'
end

# More compact logging
gem "lograge"

# Color output for our logs
gem 'colorize'

# RRD for statistics collection
gem 'rrd-ffi', group: :stats

group :test do
	# Color for minitest output
	gem 'minitest-reporters'
	
	# Code coverage report generator
	gem 'simplecov', :require => false
	
	# We do loads in after_commit callbacks so need to include them in tests
	gem 'test_after_commit'
end
```

**Comment by cvrebert** [comment]
@depili Please confirm that you're using bootstrap-sass 3.3.5.1 and please post the full exception stack trace that you're encountering.

**Comment by depili** [comment]
This is from Gemfile.lock:
```
bootstrap-sass (3.3.5.1)
      autoprefixer-rails (>= 5.0.0.1)
      sass (>= 3.3.0)
```

The full trace:
```
sprockets (3.2.0) lib/sprockets/path_utils.rb:111:in `split_subpath'
sprockets (3.2.0) lib/sprockets/path_utils.rb:126:in `block in paths_split'
sprockets (3.2.0) lib/sprockets/path_utils.rb:125:in `each'
sprockets (3.2.0) lib/sprockets/path_utils.rb:125:in `paths_split'
sprockets (3.2.0) lib/sprockets/resolve.rb:95:in `resolve_relative_path'
sprockets (3.2.0) lib/sprockets/resolve.rb:33:in `resolve'
sprockets (3.2.0) lib/sprockets/legacy.rb:66:in `resolve_with_compat'
sprockets (3.2.0) lib/sprockets/base.rb:61:in `find_asset'
sprockets (3.2.0) lib/sprockets/base.rb:89:in `[]'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:123:in `asset_digest_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:76:in `compute_asset_path'
actionview (4.2.3) lib/action_view/helpers/asset_url_helper.rb:135:in `asset_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:91:in `asset_path'
sprockets (3.2.0) lib/sprockets/sass_processor.rb:112:in `asset_path'
sprockets (3.2.0) lib/sprockets/sass_processor.rb:188:in `font_path'
sass (3.4.15) lib/sass/script/tree/funcall.rb:140:in `_perform'
sass (3.4.15) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:402:in `visit_return'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.15) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:79:in `with_base'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:8:in `visit'
sass (3.4.15) lib/sass/script/tree/funcall.rb:248:in `block (3 levels) in perform_sass_fn'
sass (3.4.15) lib/sass/script/tree/funcall.rb:248:in `each'
sass (3.4.15) lib/sass/script/tree/funcall.rb:248:in `block (2 levels) in perform_sass_fn'
sass (3.4.15) lib/sass/script/tree/funcall.rb:247:in `catch'
sass (3.4.15) lib/sass/script/tree/funcall.rb:247:in `block in perform_sass_fn'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:84:in `perform_arguments'
sass (3.4.15) lib/sass/script/tree/funcall.rb:244:in `perform_sass_fn'
sass (3.4.15) lib/sass/script/tree/funcall.rb:131:in `_perform'
sass (3.4.15) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.15) lib/sass/script/functions.rb:593:in `perform'
sass (3.4.15) lib/sass/script/functions.rb:2171:in `if'
sass (3.4.15) lib/sass/script/tree/funcall.rb:140:in `_perform'
sass (3.4.15) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.15) lib/sass/script/tree/funcall.rb:170:in `perform_arg'
sass (3.4.15) lib/sass/script/tree/funcall.rb:124:in `block in _perform'
sass (3.4.15) lib/sass/script/tree/funcall.rb:124:in `each'
sass (3.4.15) lib/sass/script/tree/funcall.rb:124:in `each_with_index'
sass (3.4.15) lib/sass/script/tree/funcall.rb:124:in `each'
sass (3.4.15) lib/sass/script/tree/funcall.rb:124:in `map'
sass (3.4.15) lib/sass/script/tree/funcall.rb:124:in `_perform'
sass (3.4.15) lib/sass/script/tree/node.rb:50:in `perform'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:394:in `visit_prop'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.15) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:79:in `with_base'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:501:in `block (2 levels) in visit_directive'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:501:in `map'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:501:in `block in visit_directive'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:500:in `visit_directive'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.15) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:79:in `with_base'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.15) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
sass (3.4.15) lib/sass/tree/visitors/base.rb:52:in `map'
sass (3.4.15) lib/sass/tree/visitors/base.rb:52:in `visit_children'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `block in visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:453:in `visit_atroot'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.15) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:79:in `with_base'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:325:in `map'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
sass (3.4.15) lib/sass/stack.rb:88:in `block in with_import'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:88:in `with_import'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:322:in `visit_import'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.15) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:79:in `with_base'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:325:in `block (2 levels) in visit_import'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:325:in `map'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:325:in `block in visit_import'
sass (3.4.15) lib/sass/stack.rb:88:in `block in with_import'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:88:in `with_import'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:322:in `visit_import'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `block in visit'
sass (3.4.15) lib/sass/stack.rb:79:in `block in with_base'
sass (3.4.15) lib/sass/stack.rb:115:in `with_frame'
sass (3.4.15) lib/sass/stack.rb:79:in `with_base'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:158:in `visit'
sass (3.4.15) lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
sass (3.4.15) lib/sass/tree/visitors/base.rb:52:in `map'
sass (3.4.15) lib/sass/tree/visitors/base.rb:52:in `visit_children'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:179:in `with_environment'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:166:in `visit_children'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `block in visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:186:in `visit_root'
sass (3.4.15) lib/sass/tree/visitors/base.rb:36:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:157:in `visit'
sass (3.4.15) lib/sass/tree/visitors/perform.rb:8:in `visit'
sass (3.4.15) lib/sass/tree/root_node.rb:36:in `css_tree'
sass (3.4.15) lib/sass/tree/root_node.rb:20:in `render'
sass (3.4.15) lib/sass/engine.rb:278:in `render'
sass-rails (5.0.3) lib/sass/rails/template.rb:47:in `evaluate'
tilt (1.4.1) lib/tilt/template.rb:103:in `render'
sprockets (3.2.0) lib/sprockets/legacy_tilt_processor.rb:25:in `call'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.2.0) lib/sprockets/loader.rb:86:in `load_asset_by_uri'
sprockets (3.2.0) lib/sprockets/loader.rb:45:in `block in load'
sprockets (3.2.0) lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
sprockets (3.2.0) lib/sprockets/loader.rb:38:in `load'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.2.0) lib/sprockets/bundle.rb:23:in `block in call'
sprockets (3.2.0) lib/sprockets/utils.rb:183:in `dfs'
sprockets (3.2.0) lib/sprockets/bundle.rb:24:in `call'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:75:in `call_processor'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:57:in `block in call_processors'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `reverse_each'
sprockets (3.2.0) lib/sprockets/processor_utils.rb:56:in `call_processors'
sprockets (3.2.0) lib/sprockets/loader.rb:86:in `load_asset_by_uri'
sprockets (3.2.0) lib/sprockets/loader.rb:45:in `block in load'
sprockets (3.2.0) lib/sprockets/loader.rb:155:in `fetch_asset_from_dependency_cache'
sprockets (3.2.0) lib/sprockets/loader.rb:38:in `load'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:20:in `block in initialize'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `yield'
sprockets (3.2.0) lib/sprockets/cached_environment.rb:47:in `load'
sprockets (3.2.0) lib/sprockets/base.rb:63:in `find_asset'
sprockets (3.2.0) lib/sprockets/environment.rb:30:in `find_asset'
sprockets (3.2.0) lib/sprockets/base.rb:89:in `[]'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:230:in `lookup_asset_for_path'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:160:in `block in stylesheet_link_tag'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `map'
sprockets-rails (2.3.2) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
app/views/layouts/application.html.slim:7:in `_app_views_layouts_application_html_slim___2772784699372975735_70282276479020'
actionview (4.2.3) lib/action_view/template.rb:145:in `block in render'
activesupport (4.2.3) lib/active_support/notifications.rb:166:in `instrument'
actionview (4.2.3) lib/action_view/template.rb:333:in `instrument'
actionview (4.2.3) lib/action_view/template.rb:143:in `render'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:66:in `render_with_layout'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
actionview (4.2.3) lib/action_view/renderer/template_renderer.rb:14:in `render'
actionview (4.2.3) lib/action_view/renderer/renderer.rb:42:in `render_template'
actionview (4.2.3) lib/action_view/renderer/renderer.rb:23:in `render'
actionview (4.2.3) lib/action_view/rendering.rb:100:in `_render_template'
actionpack (4.2.3) lib/action_controller/metal/streaming.rb:217:in `_render_template'
actionview (4.2.3) lib/action_view/rendering.rb:83:in `render_to_body'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
actionpack (4.2.3) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
actionpack (4.2.3) lib/abstract_controller/rendering.rb:25:in `render'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/vpalmu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
activesupport (4.2.3) lib/active_support/core_ext/benchmark.rb:12:in `ms'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:43:in `render'
actionpack (4.2.3) lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
app/controllers/slides_controller.rb:26:in `index'
actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
rack (1.6.4) lib/rack/etag.rb:24:in `call'
rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
rack (1.6.4) lib/rack/head.rb:13:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.4) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
railties (4.2.3) lib/rails/engine.rb:518:in `call'
railties (4.2.3) lib/rails/application.rb:165:in `call'
rack (1.6.4) lib/rack/content_length.rb:15:in `call'
thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
thin (1.6.3) lib/thin/connection.rb:84:in `catch'
thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
thin (1.6.3) lib/thin/connection.rb:53:in `process'
faye-websocket (0.9.2) lib/faye/adapters/thin.rb:40:in `process'
thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
faye-websocket (0.9.2) lib/faye/adapters/thin.rb:44:in `receive_data'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run_machine'
eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
thin (1.6.3) lib/thin/server.rb:162:in `start'
rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
rack (1.6.4) lib/rack/server.rb:286:in `start'
railties (4.2.3) lib/rails/commands/server.rb:80:in `start'
railties (4.2.3) lib/rails/commands/commands_tasks.rb:80:in `block in server'
railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `tap'
railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `server'
railties (4.2.3) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
railties (4.2.3) lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:10:in `require'
bin/rails:10:in `<top (required)>'
spring (1.3.6) lib/spring/client/rails.rb:28:in `load'
spring (1.3.6) lib/spring/client/rails.rb:28:in `call'
spring (1.3.6) lib/spring/client/command.rb:7:in `call'
spring (1.3.6) lib/spring/client.rb:26:in `run'
spring (1.3.6) bin/spring:48:in `<top (required)>'
spring (1.3.6) lib/spring/binstub.rb:11:in `load'
spring (1.3.6) lib/spring/binstub.rb:11:in `<top (required)>'
bin/spring:16:in `require'
bin/spring:16:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
```

This same error has also been asked in stackoverflow by someone else:
http://stackoverflow.com/questions/29993823/repeating-error-undefined-method-start-with-for-nilnilclass

**Comment by depili** [comment]
Digging little deeper has revealed that the error seems to go away if I only @import bootstrap-sprokets and bootstrap, instead of the current bootstrap-custom and digging a even deeper reveals that for some reason importing _superhero_variables.scss and bootstrap-sprokets is the trigger.

Will now try to narrow down what part of the bootstrap-theme triggers this.

**Comment by cvrebert** [comment]
I'd speculate that the `$icon-font-*` variables in `_superhero_variables.scss` are somehow to blame.

**Comment by depili** [comment]
Success, the stuff inside a slightly modified superhero bootstrap theme that triggers this error is setting the glyphicons:
```
//== Iconography
//
//## Specify custom location and filename of the included Glyphicons icon font. Useful for those including Bootstrap via Bower.

//** Load fonts from this directory.
$icon-font-path:          "../fonts/";
//** File name for all font files.
$icon-font-name:          "glyphicons-halflings-regular";
//** Element ID within SVG icon file.
$icon-font-svg-id:        "glyphicons_halflingsregular";
```

The real question is then what broke this

**Comment by cvrebert** [comment]
Duplicate of https://github.com/thomaspark/bootswatch/issues/453 ?

**Comment by depili** [comment]
I'm not using bootswatches gem, got the sass settings file only from https://bootswatch.com/ but the issue seems to be the same otherwise.

**Comment by cvrebert** [comment]
Closing in favor of that Bootswatch bug then.

**Comment by MrHubble** [comment]
@depili how do you use bootswatch with the bootstrap-sass gem without using the bootswatch-rails gem?

>Simply download a CSS file and replace the one in Bootstrap

I'm not sure how to replace the bootstrap-sass gem bootstrap file
